{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2c7ce7ba_dca905f7",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1006192
      },
      "writtenOn": "2021-04-28T20:05:00Z",
      "side": 1,
      "message": "Have you checked if also stable-3.1 has the same issue?",
      "revId": "56cdb9f74b32bf13d322c01f84e94ff4e877f7fd",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}